version: "3.7"

services: 
  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose: 
      - 5000

  springboot:
    build: ./SpringBootPractiseApp
    container_name: spring_boot
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80

  mysql_db:
    build: ./mysql
    container_name: db
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_db
      MYSQL_USER: adithya
      MYSQL_PASSWORD: 1234
    