kind: Service
apiVersion: v1
metadata:
  name: springboot
  labels:
    name: springboot
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: springboot
  type: NodePort 